version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "8000:8000"
    ports:
      - "8000:8000"
    environment:
      - key=sdf7c899xvv9sb1nm4jj

  frontend:
    build: ./frontend
    expose:
      - "5000:5000"
    ports:
      - "5000:5000"

    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000